include $(TOPDIR)/rules.mk

LUCI_NAME:=luci-app-zeroclaw
PKG_VERSION:=1.1
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for ZeroClaw
LUCI_DEPENDS:=+luci-base +zeroclaw
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
